services:
  mellophone:
    image: curs/mellophone2:1.6.1
    ports:
      - "8082:8082"
    volumes:
      - ./docker-config/config.xml:/config/config.xml

  db:
    image: postgres:16.3-alpine
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./docker-config/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
